apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.Namespace }}
  name: {{ .Values.Servicename }}
spec:
  ports:
    - port: {{ .Values.containers.port }}
      targetPort: {{ .Values.containers.port }}
      protocol: TCP
  type: NodePort
  selector:
    {{- toYaml .Values.selector| nindent 4 }}